### ISSUE TITLE
External display solid color oversized  

### ISSUE THREAD

**Issue by the3ye** [igorkulman/ChangeMenuBarColor#49] opened 2021-02-08 15:02 UTC
I’ll create new Issue as this is not fixed in 0.9.0
Have same issue. Using external monitor 2560 × 1440 px. When I set wallpaper (using static, stock one) and use `ChangeMenuBarColor SolidColor "#CCCCCC" --all-displays` I’m getting wallpaper with overlay color way too big on the external screen (internal screen is OK).
![external](https://user-images.githubusercontent.com/13607809/106724189-33d06900-6608-11eb-9425-71808d148aef.jpg)

_Originally posted by @the3ye in https://github.com/igorkulman/ChangeMenuBarColor/issues/44#issuecomment-772355050_

**Comment by igorkulman** [comment] 2021-02-08 15:04
Duplicate of #44

**Closed by igorkulman** 2021-02-08 15:04 UTC
