### ISSUE TITLE
Disable/Delete ChangeMenuBarColor and revert to default macOS menu bar

### ISSUE THREAD

**Issue by benyamynbrkyc** [igorkulman/ChangeMenuBarColor#37] opened 2021-01-13 17:09 UTC
Since the readme does not specify the exact steps, I was wondering how can I remove the tool, in case I don't like it.

**Comment by igorkulman** [comment] 2021-01-13 17:15
Duplicate of #27

**Closed by igorkulman** 2021-01-13 17:15 UTC
